export const BULK_STAR_CONSTANTS = {
  MAX_EVENTS_PER_BATCH: 2000,
  MAX_PAGINATION_CLICKS: 100,
  PAGINATION_CLICK_TIMEOUT_MS: 10_000,
  PAGINATION_CLICK_DELAY_MS: 300,
  STAR_MESSAGE_DELAY_MS: 10,
  BATCH_SIZE: 50,
  BATCH_THRESHOLD: 200,
  RETRY_DELAY_MS: 1000,
  MAX_RETRIES: 2,
  ERROR_ABORT_THRESHOLD: 0.5,
  SUMMARY_DISPLAY_MS: 5000,
  BUTTON_VIEWPORT_OFFSET_PX: 16,
} as const;
